'use client';

interface TicketPreviewProps {
  incidentId: string;
  summary: string;
  status: string;
  agent: 'npu' | 'cloud';
  resolution: string;
  confidence: number;
  latency: number;
  category?: string;
  estimatedTime?: string;
}

export function TicketPreview({
  incidentId,
  summary,
  status,
  agent,
  resolution,
  confidence,
  latency,
  category,
  estimatedTime,
}: TicketPreviewProps) {
  const handleCopy = () => {
    const ticketText = generateTicketText();
    navigator.clipboard.writeText(ticketText);
    alert('Ticket content copied to clipboard!');
  };

  const generateTicketText = () => {
    return `Incident #${incidentId}
Status: ${status}
Resolved by: AI Agent (${agent === 'npu' ? 'T1 - Local NPU' : 'T2+ - Cloud'})
Resolution Time: ${(latency / 1000).toFixed(1)}s
Confidence: ${(confidence * 100).toFixed(0)}%
${category ? `Category: ${category}` : ''}
${estimatedTime ? `Estimated Time: ${estimatedTime}` : ''}

Summary:
${summary}

Resolution Steps:
${resolution}

Agent Details:
- Agent: ${agent === 'npu' ? 'NPU (Local Edge)' : 'Cloud (Azure OpenAI)'}
- Model: ${agent === 'npu' ? 'Phi-3.5-mini-instruct (3.8B)' : 'GPT-4o'}
- Hardware: ${agent === 'npu' ? 'Intel Core Ultra NPU' : 'Cloud Compute'}
- Inference Time: ${(latency / 1000).toFixed(1)}s

---
Generated by Hybrid AI Service Desk
Edge-to-Cloud Intelligent Routing System`;
  };

  return (
    <div className="border border-gray-200 rounded-lg p-4 bg-white">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-lg font-semibold flex items-center gap-2">
          <span>📄</span>
          <span>Ticket Output Preview</span>
        </h3>
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="px-3 py-1 text-sm bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
          >
            Copy to Clipboard
          </button>
        </div>
      </div>

      <div className="bg-gray-50 border border-gray-300 rounded p-4 font-mono text-sm space-y-3">
        <div>
          <div className="font-bold text-gray-700">Incident #{incidentId}</div>
          <div className="text-gray-600">
            Status: <span className="font-semibold text-green-600">{status}</span>
          </div>
          <div className="text-gray-600">
            Resolved by: AI ({agent === 'npu' ? 'T1 - Local NPU' : 'T2+ - Cloud'})
          </div>
          <div className="text-gray-600">Resolution Time: {(latency / 1000).toFixed(1)}s</div>
          <div className="text-gray-600">Confidence: {(confidence * 100).toFixed(0)}%</div>
          {category && <div className="text-gray-600">Category: {category}</div>}
          {estimatedTime && <div className="text-gray-600">Estimated Time: {estimatedTime}</div>}
        </div>

        <div className="border-t border-gray-300 pt-3">
          <div className="font-bold text-gray-700 mb-2">Summary:</div>
          <div className="text-gray-600">{summary}</div>
        </div>

        <div className="border-t border-gray-300 pt-3">
          <div className="font-bold text-gray-700 mb-2">Resolution Steps:</div>
          <div className="text-gray-600 whitespace-pre-wrap">{resolution}</div>
        </div>

        <div className="border-t border-gray-300 pt-3">
          <div className="font-bold text-gray-700 mb-2">Agent Details:</div>
          <div className="text-gray-600 space-y-1">
            <div>- Agent: {agent === 'npu' ? 'NPU (Local Edge)' : 'Cloud (Azure OpenAI)'}</div>
            <div>- Model: {agent === 'npu' ? 'Phi-3.5-mini-instruct (3.8B)' : 'GPT-4o'}</div>
            <div>- Hardware: {agent === 'npu' ? 'Intel Core Ultra NPU' : 'Cloud Compute'}</div>
            <div>- Inference Time: {(latency / 1000).toFixed(1)}s</div>
          </div>
        </div>
      </div>
    </div>
  );
}
